M48
; DRILL file {KiCad 9.0.3} date 2025-10-08T17:43:42-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-10-08T17:43:42-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X-3.6066Y1.4949
X-3.4457Y1.334
T2
X-3.6576Y2.3066
X-2.3977Y1.0074
X-1.1379Y2.3066
M30
